Repository YiGu-Studio/DocsModdingBannerlordCN, pull requests merged in 2020-10, with the labels that each got.

#29 Add original files in Asset Types
  content/en/Asset Management/Asset Types/Asset Naming Conventions/_index.md
  content/en/Asset Management/Asset Types/Bodies/_index.md
  content/en/Asset Management/Asset Types/Materials/_index.md
  content/en/Asset Management/Asset Types/Meshes/_index.md
  content/en/Asset Management/Asset Types/Overriding Assets/_index.md
  content/en/Asset Management/Asset Types/Overriding Assets/material_override.png
  content/en/Asset Management/Asset Types/Overriding Assets/metamesh_override.png
  content/en/Asset Management/Asset Types/Overriding Assets/physics_shape_override.png
  content/en/Asset Management/Asset Types/Overriding Assets/texture_override.png
  content/en/Asset Management/Asset Types/Overriding Scenes Prefabs/_index.md
  content/en/Asset Management/Asset Types/Path/_index.md
  content/en/Asset Management/Asset Types/Prefabs/_index.md
  content/en/Asset Management/Asset Types/Scripts/_index.md
  content/en/Asset Management/Asset Types/Textures/_index.md
  content/en/Asset Management/Asset Types/_index.md
  content/en/Asset Management/_index.md
  content/zh/Asset Management/Asset Types/Asset Naming Conventions/_index.md
  content/zh/Asset Management/Asset Types/Bodies/_index.md
  content/zh/Asset Management/Asset Types/Materials/_index.md
  content/zh/Asset Management/Asset Types/Meshes/_index.md
  content/zh/Asset Management/Asset Types/Overriding Assets/_index.md
  content/zh/Asset Management/Asset Types/Overriding Assets/material_override.png
  content/zh/Asset Management/Asset Types/Overriding Assets/metamesh_override.png
  content/zh/Asset Management/Asset Types/Overriding Assets/physics_shape_override.png
  content/zh/Asset Management/Asset Types/Overriding Assets/texture_override.png
  content/zh/Asset Management/Asset Types/Overriding Scenes Prefabs/_index.md
  content/zh/Asset Management/Asset Types/Path/_index.md
  content/zh/Asset Management/Asset Types/Prefabs/_index.md
  content/zh/Asset Management/Asset Types/Scripts/_index.md
  content/zh/Asset Management/Asset Types/Textures/_index.md
Labels: documentation

#36 Add some original files in Scene Editor
  content/en/Editor/Scene Editor/Entity Inspector/_index.md
  content/en/Editor/Scene Editor/Entity Inspector/gizmo_rotate.png
  content/en/Editor/Scene Editor/Entity Inspector/gizmo_scale.png
  content/en/Editor/Scene Editor/Entity Inspector/gizmo_translate.png
  content/en/Editor/Scene Editor/Entity Inspector/scale_locked.png
  content/en/Editor/Scene Editor/Entity Inspector/scale_unlocked.png
  content/en/Editor/Scene Editor/Entity Inspector/transform.png
  content/en/Editor/Scene Editor/Mass Selection/_index.md
  content/en/Editor/Scene Editor/Mass Selection/after_selection.png
  content/en/Editor/Scene Editor/Mass Selection/before_selection.png
  content/en/Editor/Scene Editor/Mass Selection/rotated.png
  content/en/Editor/Scene Editor/Mass Selection/script.png
  content/en/Editor/Scene Editor/Nav Mesh Inspector/_index.md
  content/en/Editor/Scene Editor/Nav Mesh Inspector/auto_generation_parameters.png
  content/en/Editor/Scene Editor/Nav Mesh Inspector/debugging_tools.png
  content/en/Editor/Scene Editor/Nav Mesh Inspector/generation_tools.png
  content/en/Editor/Scene Editor/PRT/_index.md
  content/en/Editor/Scene Editor/PRT/diffuse_ambient.png
  content/en/Editor/Scene Editor/PRT/gi_operations_tab.png
  content/en/Editor/Scene Editor/PRT/grid1.png
  content/en/Editor/Scene Editor/PRT/grid2.png
  content/en/Editor/Scene Editor/PRT/lasso.png
  content/en/Editor/Scene Editor/PRT/prt_probes.png
  content/en/Editor/Scene Editor/PRT/prt_ss_gi.png
  content/en/Editor/Scene Editor/PRT/prt_ss_sky_access.png
  content/en/Editor/Scene Editor/Terrain Mesh Blend/_index.md
  content/en/Editor/Scene Editor/Terrain Mesh Blend/editor_props.png
  content/en/Editor/Scene Editor/Terrain Mesh Blend/with_mesh_blend.png
  content/en/Editor/Scene Editor/Terrain Mesh Blend/without_mesh_blend.png
  content/en/Editor/Scene Editor/Terrain Resize/_index.md
  content/en/Editor/Scene Editor/Terrain Resize/append.png
  content/en/Editor/Scene Editor/Terrain Resize/delete.png
  content/en/Editor/Scene Editor/Terrain Resize/resize_panel.png
Labels: documentation

#34 Add original files in Bannerlord Missions
  content/en/Bannerlord Missions/Destructible Component/Debris.png
  content/en/Bannerlord Missions/Destructible Component/Debris_Hierarchy.png
  content/en/Bannerlord Missions/Destructible Component/Script_Overview.png
  content/en/Bannerlord Missions/Destructible Component/SiegeBarricade_Hierarchy_Edited.png
  content/en/Bannerlord Missions/Destructible Component/SiegeBarricade_Script.png
  content/en/Bannerlord Missions/Destructible Component/SiegeBarricade_States.png
  content/en/Bannerlord Missions/Destructible Component/Wall_Hierarchy_Edited.png
  content/en/Bannerlord Missions/Destructible Component/Wall_Origin_Debris.png
  content/en/Bannerlord Missions/Destructible Component/Wall_Origin_Debris_Hierarchy.png
  content/en/Bannerlord Missions/Destructible Component/Wall_Origin_Merlon.png
  content/en/Bannerlord Missions/Destructible Component/Wall_Origin_Merlon_Hierarchy.png
  content/en/Bannerlord Missions/Destructible Component/Wall_Script.png
  content/en/Bannerlord Missions/Destructible Component/_index.md
  content/en/Bannerlord Missions/Mission Tactical Positions/1.png
  content/en/Bannerlord Missions/Mission Tactical Positions/2.png
  content/en/Bannerlord Missions/Mission Tactical Positions/3.png
  content/en/Bannerlord Missions/Mission Tactical Positions/4.png
  content/en/Bannerlord Missions/Mission Tactical Positions/5.png
  content/en/Bannerlord Missions/Mission Tactical Positions/6.png
  content/en/Bannerlord Missions/Mission Tactical Positions/7.png
  content/en/Bannerlord Missions/Mission Tactical Positions/_index.md
  content/en/Bannerlord Missions/Scene Barrier Builder/_index.md
  content/en/Bannerlord Missions/Scene Barrier Builder/add_path.png
  content/en/Bannerlord Missions/Scene Barrier Builder/change_barrier.png
  content/en/Bannerlord Missions/Scene Barrier Builder/create_barrier.png
  content/en/Bannerlord Missions/Scene Barrier Builder/create_path.png
  content/en/Bannerlord Missions/Scene Barrier Builder/name_path.png
  content/en/Bannerlord Missions/Scene Spawn Point Guide/_index.md
  content/en/Bannerlord Missions/Scene Spawn Point Guide/document1.png
  content/en/Bannerlord Missions/Script Component Callbacks/_index.md
  content/en/Bannerlord Missions/Spawn Point Debug Tool/_index.md
  content/en/Bannerlord Missions/Spawn Point Debug Tool/tooldocument1.png
  content/en/Bannerlord Missions/Spawn Point Debug Tool/tooldocument2.png
  content/en/Bannerlord Missions/Spawn Point Debug Tool/tooldocument4.png
  content/en/Bannerlord Missions/Spawn Point Debug Tool/tooldocument5.png
  content/en/Bannerlord Missions/Spawn Point Debug Tool/tooldocument6.png
  content/en/Bannerlord Missions/_index.md
Labels: documentation

#37 Check Hugo Build when PR
  .github/workflows/hugo_build.yml
Labels: enhancement

#43 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#45 Translate: Asset Management/Quick Guides/_index.md
  content/zh/Asset Management/Quick Guides/_index.md
Labels: translation

#56 Translated index.md under Asset Types Folder
  content/zh/Asset Management/Asset Types/_index.md
Labels: translation
